# Generated by Django 2.2 on 2019-04-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0003_message_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=1000),
        ),
    ]
