# Generated by Django 2.2 on 2019-04-08 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('msg', '0005_auto_20190408_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='reciever',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='sender',
        ),
        migrations.AddField(
            model_name='thread',
            name='user_1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='user_2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
