# Generated by Django 2.2 on 2019-04-08 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0010_auto_20190408_1756'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
    ]
