# Generated by Django 2.2 on 2019-04-08 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0011_auto_20190408_1757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-updated_at']},
        ),
    ]
