# Generated by Django 2.2 on 2019-04-09 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0012_auto_20190408_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='user_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_1_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='thread',
            name='user_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_2_threads', to=settings.AUTH_USER_MODEL),
        ),
    ]
